// an analog clock :)
// has a range of 0-23 hours

int hourNow = 0;
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);
hourNow++;
Console.WriteLine(hourNow % 24);